FROM tck-xinan-registry.cn-chengdu.cr.aliyuncs.com/wair/lerobot:0.0.2

ARG PIP="/root/miniconda3/envs/gr00t/bin/pip"

WORKDIR /workspace/lerobot

COPY . .

RUN ${PIP} install -e ".[pi]" -i https://pypi.tuna.tsinghua.edu.cn/simple/

ENTRYPOINT []
CMD ["bash", "-c", "source /root/miniconda3/bin/activate gr00t && python src/lerobot/scripts/lerobot_http.py"]